CREATE DATABASE universe;
\c universe
CREATE TABLE galaxy (galaxy_id SERIAL PRIMARY KEY, name VARCHAR(100) UNIQUE NOT NULL, description TEXT, age_in_millions_of_years INT, distance_from_earth NUMERIC(10,2), has_life BOOLEAN, is_spherical BOOLEAN NOT NULL);
CREATE TABLE star (star_id SERIAL PRIMARY KEY, name VARCHAR(100) UNIQUE NOT NULL, galaxy_id INT NOT NULL REFERENCES galaxy(galaxy_id), age_in_millions_of_years INT, distance_from_earth NUMERIC(10,2), is_spherical BOOLEAN NOT NULL, has_life BOOLEAN);
CREATE TABLE planet (planet_id SERIAL PRIMARY KEY, name VARCHAR(100) UNIQUE NOT NULL, star_id INT NOT NULL REFERENCES star(star_id), age_in_millions_of_years INT, has_life BOOLEAN NOT NULL, is_spherical BOOLEAN NOT NULL, distance_from_earth NUMERIC(12,2));
CREATE TABLE moon (moon_id SERIAL PRIMARY KEY, name VARCHAR(100) UNIQUE NOT NULL, planet_id INT NOT NULL REFERENCES planet(planet_id), age_in_millions_of_years INT, is_spherical BOOLEAN NOT NULL, has_life BOOLEAN NOT NULL, distance_from_earth NUMERIC(12,2));
CREATE TABLE comet (comet_id SERIAL PRIMARY KEY, name VARCHAR(100) UNIQUE NOT NULL, galaxy_id INT NOT NULL REFERENCES galaxy(galaxy_id), age_in_millions_of_years INT NOT NULL, is_spherical BOOLEAN NOT NULL, distance_from_earth NUMERIC(12,2));
INSERT INTO galaxy (name,description,age_in_millions_of_years,distance_from_earth,has_life,is_spherical) VALUES ('Milky Way','Our home galaxy',13600,0,TRUE,FALSE),('Andromeda','Nearest large galaxy',10000,2537000,NULL,FALSE),('Triangulum','Third largest in Local Group',9000,2730000,NULL,FALSE),('Whirlpool','Classic spiral galaxy',400,23000000,NULL,FALSE),('Sombrero','Bright elliptical in Virgo',13200,29000000,NULL,TRUE),('Pinwheel','Face-on spiral in Ursa Major',1000,21000000,NULL,FALSE);
INSERT INTO star (name,galaxy_id,age_in_millions_of_years,distance_from_earth,is_spherical,has_life) VALUES ('Sun',1,4603,0,TRUE,TRUE),('Sirius',1,200,9,TRUE,FALSE),('Alpha Centauri',1,5000,4,TRUE,NULL),('Betelgeuse',1,8,700,TRUE,FALSE),('Vega',1,455,25,TRUE,FALSE),('Rigel',1,8,860,TRUE,FALSE);
INSERT INTO planet (name,star_id,age_in_millions_of_years,has_life,is_spherical,distance_from_earth) VALUES ('Mercury',1,4503,FALSE,TRUE,0),('Venus',1,4503,FALSE,TRUE,0),('Earth',1,4543,TRUE,TRUE,0),('Mars',1,4503,FALSE,TRUE,0),('Jupiter',1,4503,FALSE,TRUE,0),('Saturn',1,4503,FALSE,TRUE,0),('Uranus',1,4503,FALSE,TRUE,0),('Neptune',1,4503,FALSE,TRUE,0),('Proxima b',3,4853,FALSE,TRUE,4),('Proxima c',3,4853,FALSE,TRUE,4),('Sirius Ab',2,200,FALSE,TRUE,9),('Vega b',5,455,FALSE,TRUE,25);
INSERT INTO moon (name,planet_id,age_in_millions_of_years,is_spherical,has_life,distance_from_earth) VALUES ('Moon',3,4500,TRUE,FALSE,0),('Phobos',4,4000,FALSE,FALSE,0),('Deimos',4,4000,FALSE,FALSE,0),('Io',5,4500,TRUE,FALSE,0),('Europa',5,4500,TRUE,FALSE,0),('Ganymede',5,4500,TRUE,FALSE,0),('Callisto',5,4500,TRUE,FALSE,0),('Mimas',6,4500,TRUE,FALSE,0),('Enceladus',6,4500,TRUE,FALSE,0),('Tethys',6,4500,TRUE,FALSE,0),('Dione',6,4500,TRUE,FALSE,0),('Rhea',6,4500,TRUE,FALSE,0),('Titan',6,4500,TRUE,FALSE,0),('Iapetus',6,4500,TRUE,FALSE,0),('Miranda',7,4500,FALSE,FALSE,0),('Ariel',7,4500,TRUE,FALSE,0),('Umbriel',7,4500,TRUE,FALSE,0),('Titania',7,4500,TRUE,FALSE,0),('Oberon',7,4500,TRUE,FALSE,0),('Triton',8,4500,TRUE,FALSE,0);
INSERT INTO comet (name,galaxy_id,age_in_millions_of_years,is_spherical,distance_from_earth) VALUES ('Halley',1,4600,FALSE,0),('Hale-Bopp',1,4600,FALSE,0),('Churyumov',1,4600,FALSE,0);

